### ISSUE TITLE
`blurb test` lacks test data

### ISSUE THREAD

**Issue by pitrou** [python/core-workflow#144]
```
$ ~/cpython/default/python -m blurb.blurb test
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antoine/cpython/default/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/antoine/cpython/default/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 1514, in <module>
    main()
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 1429, in main
    sys.exit(fn(*args))
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 742, in test
    fn()
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 595, in test_files
    with pushd(self.directory):
  File "/home/antoine/cpython/core-workflow/blurb/blurb.py", line 181, in __enter__
    os.chdir(self.path)
FileNotFoundError: [Errno 2] No such file or directory: 'tests/fail'
```

**Comment by pitrou** [comment]
@larryhastings
