### ISSUE TITLE
blurb uses system python, but expect python 3

### ISSUE THREAD

**Issue by nirs** [python/core-workflow#153]
After installing blurb:

    pip install --user blurb

It fails, using system python:

```
$ blurb
Traceback (most recent call last):
  File "/home/nsoffer/.local/bin/blurb", line 9, in <module>
    load_entry_point('blurb==1.0.0.post1', 'console_scripts', 'blurb')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/nsoffer/.local/lib/python2.7/site-packages/blurb.py", line 125
    def textwrap_body(body, *, subsequent_indent=''):
                             ^
SyntaxError: invalid syntax
```

**Comment by nirs** [comment]
Strangely, it fails also with python 3:

```
$ pip3 install --user blurb
...
Successfully installed blurb
$ blurb
Traceback (most recent call last):
  File "/home/nsoffer/.local/bin/blurb", line 7, in <module>
    from blurb import main
  File "/home/nsoffer/.local/lib/python3.5/site-packages/blurb.py", line 166
    return input(f"[{prompt}> ")
                              ^
SyntaxError: invalid syntax

```

**Comment by Mariatta** [comment]
The version of blurb that is in PyPI right now requires Python 3.6.

**Comment by nirs** [comment]
Maybe the metadata in pypi is not correct, or this is pip issue, letting the user install a version which is not compatible with the current python version?

**Comment by brettcannon** [comment]
@nirs if your version of pip is too old -- which is quite possible if you're using a system-installed Python -- then it won't have the logic to check for `python-requires` as set on PyPI.
