### ISSUE TITLE
blurb does not support command line options in EDITOR/GIT_EDITOR

### ISSUE THREAD

**Issue by nirs** [python/core-workflow#162]
On windows users may like to configure their editor with options:
```
$ git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -nosession"
```
See https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

blurb assume that EDITOR/GIT_EDITOR environment variables are executable names, so it will fail to run the user configured editor:

$ EDITOR="'foo bar' --baz" ../../core-workflow/blurb/blurb.py 
Traceback (most recent call last):
  File "../../core-workflow/blurb/blurb.py", line 1527, in <module>
    main()
  File "../../core-workflow/blurb/blurb.py", line 1487, in main
    sys.exit(fn(*filtered_args, **kwargs))
  File "../../core-workflow/blurb/blurb.py", line 804, in add
    subprocess.run([editor, tmp_path])
  File "/usr/lib64/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: "'foo bar' --baz"

**Comment by nirs** [comment]
Here is an example run using command with spaces (typical on windows) and command line options:

Creating editor with spaces in path:
```
ln -s /usr/bin/vim 'my_editor'
```
Trying to use 'my editor' with blurb master:
```
$ EDITOR="$PWD/'my editor' +25" ../../core-workflow/blurb/blurb.py
Traceback (most recent call last):
  File "../../core-workflow/blurb/blurb.py", line 1527, in <module>
    main()
  File "../../core-workflow/blurb/blurb.py", line 1487, in main
    sys.exit(fn(*filtered_args, **kwargs))
  File "../../core-workflow/blurb/blurb.py", line 804, in add
    subprocess.run([editor, tmp_path])
  File "/usr/lib64/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: "/home/nsoffer/src/cpython/debug/'my editor' +25"
```

**Comment by larryhastings** [comment]
Please see https://github.com/python/core-workflow/pull/206 .
