### ISSUE TITLE
pip install blurb successfully installs with Python < 3.5

### ISSUE THREAD

**Issue by rodrigc** [python/core-workflow#174]
According to: https://github.com/python/core-workflow/issues/173#issuecomment-324539108

installing blurb should fail if the Python version is too old.

However, I was able to do this with Python 2.7:

```
python --version
Python 2.7.10

python -m pip install blurb

Collecting blurb
  Downloading blurb-1.0.tar.gz
Installing collected packages: blurb
  Running setup.py install for blurb ... done
Successfully installed blurb-1.0
```

Trying to run blurb then fails under Python 2.7 with a SyntaxError.

**Comment by mlouielu** [comment]
Debugging from pip:

```
$ python2 -m pip install blurb -v
  Analyzing links from page https://pypi.python.org/simple/blurb/                                                                                                                                                                                Skipping link https://pypi.python.org/packages/0b/f6/e7cd43f9c3d582e5640dffe6f266694ac78ee45712993a7efeb6099650be/blurb-1.0.2.dev1-py3-none-any.whl#md5=d240df35570e23971cbf8b3058c1d6e1 (from https://pypi.python.org/simple/blurb/) (re
quires-python:>=3.5); it is not compatible with this Python                                                            
    Found link https://pypi.python.org/packages/29/56/3a0bf4c03dd31522a503897f08eb292257e1641958c5a2d56d91ef8a337b/blurb-1.0.tar.gz#md5=92a39cc2d87e9cf2bad61391411aa567 (from https://pypi.python.org/simple/blurb/), version: 1.0              Skipping link https://pypi.python.org/packages/29/9f/07da5243547f834a54064d049b3ec1f2d1954a2115c8883ab95abd6581a7/blurb-1.0-py3.6.egg#md5=0b792fda61161da874aa3242ca8b9ac3 (from https://pypi.python.org/simple/blurb/); unsupported arch
ive format: .egg                                                                                                       
    Skipping link https://pypi.python.org/packages/2b/23/51a7bc8a9dc6fe04ba5635c96000c93e738bfe4d11e008b0c04bc5e519bc/blurb-1.0.1.post1-py3-none-any.whl#md5=114f7f9d3851d6e9cef2ab1d0b351ac4 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5); it is not compatible with this Python                                                          
    The package https://pypi.python.org/packages/32/dd/0a5e12bd32380fda9229eec68d5a3b2da014ebca8075ecf8cd3c4b18bab8/blurb-1.0.1.post1.tar.gz#md5=00380bc2a84870c5a6e0cc4e83ea7636 (from https://pypi.python.org/simple/blurb/) (requires-pyth
on:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5                                                                                                                                                    The package https://pypi.python.org/packages/3d/d3/b17ae953f530f9287e29e86acaec4c6a858eae576ae487f3348edbd0b6af/blurb-1.0.0.post1.tar.gz#md5=082bb8a9edffff0b9095327c1f7ca860 (from https://pypi.python.org/simple/blurb/) (requires-pyth
on:>=3.6) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.6                          
    The package https://pypi.python.org/packages/4b/f3/76ea04c73110e5b936c1e164e5cbdbbebb6fb0a239b0b9198a932ec17bda/blurb-1.0.4.tar.gz#md5=7b730fc19cc412fc66ffdba7bd261473 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5                               
    Skipping link https://pypi.python.org/packages/59/3f/7fad7eb4044573c3c442945b8efd97b70a65392a0290c3c10552d8d122a9/blurb-1.0.1-py3-none-any.whl#md5=a6e52e66796167012b09af71b795584d (from https://pypi.python.org/simple/blurb/) (require
s-python:>=3.6); it is not compatible with this Python                                                                                                                                                                                           Skipping link https://pypi.python.org/packages/76/05/16a4ef11265cd85555e501c61fa26deada04aa4856f889cec0f6363fa91a/blurb-1.0-py3-none-any.whl#md5=c6adc39f792db71488cac24fa6dfe716 (from https://pypi.python.org/simple/blurb/); it is not
 compatible with this Python                                                                                           
    The package https://pypi.python.org/packages/81/38/9c55685c7162dcaace7a034ff97e2c0253c965501378bd703479da9c282b/blurb-1.0.1.tar.gz#md5=cd3cc72ee9465a371f1f609fb87a0130 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.6                               
    The package https://pypi.python.org/packages/b8/ac/bf076a991f9c38eb7c140eebeffb2d9f6ae1c18b4673862461aa572a43ec/blurb-1.0.2.dev1.tar.gz#md5=bfda3e4deae686c122a5ff10ea0ae6c8 (from https://pypi.python.org/simple/blurb/) (requires-pytho
n:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5                                                                                                                                                     Skipping link https://pypi.python.org/packages/bc/92/ce7ffb09fc98975a4718acc89e180e6e8410f8beb518f4fbcb55af2005eb/blurb-1.0.0.post1-py3-none-any.whl#md5=4faf1d37bbb17502b5471dfa84ada12e (from https://pypi.python.org/simple/blurb/) (r
equires-python:>=3.6); it is not compatible with this Python                                                                                                                                                                                 
    Skipping link https://pypi.python.org/packages/be/52/acf0440fd5107f4ffb104d4cf376542f648aa3933a82753ca9590a814147/blurb-1.0.4-py3-none-any.whl#md5=b0ea6f7f34345e34412e0037168fa9ad (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5); it is not compatible with this Python                                                                                                                                                                                           Skipping link https://pypi.python.org/packages/c2/27/6bb9429bc126e6796a25eabbf3f472170e99d68aa2b3a8372f7a13e1babc/blurb-1.0.3-py3-none-any.whl#md5=3ffec5130dad3f85e6f4c8825d9b96e3 (from https://pypi.python.org/simple/blurb/) (require
s-python:>=3.5); it is not compatible with this Python     
    The package https://pypi.python.org/packages/ee/be/62c216959f57c97d277c730978b06beb0a9ce0ffc7dcaa83535ab6440c6e/blurb-1.0.3.tar.gz#md5=90c936b71fd46667a67a3945b7107b16 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3
.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5                               
  Using version 1.0 (newest of versions: 1.0)                                                                          
  Looking up "https://pypi.python.org/packages/29/56/3a0bf4c03dd31522a503897f08eb292257e1641958c5a2d56d91ef8a337b/blurb-1.0.tar.gz" in the cache                                                                
  Current age based on date: 48                            
  Freshness lifetime from max-age: 31557600                
  The response is "fresh", returning cached response       
  31557600 > 48                                            
  Using cached blurb-1.0.tar.gz                                                                                        
  Downloading from URL https://pypi.python.org/packages/29/56/3a0bf4c03dd31522a503897f08eb292257e1641958c5a2d56d91ef8a337b/blurb-1.0.tar.gz#md5=92a39cc2d87e9cf2bad61391411aa567 (from https://pypi.python.org/simple/blurb/)
  Running setup.py (path:/tmp/pip-build-3VJH8B/blurb/setup.py) egg_info for package blurb                             

```

It seems pip fallback to 1.0.0 which didn't constraint the version, thus python 2.7 successful to install.

Maybe it will need to remove from pypi manally for the first version for blurb.

**Comment by larryhastings** [comment]
Okay, if pip allows you to install blurb under python < 3.5, then that's a bug.  But we're not going to fix blurb so it runs under python < 3.5.

**Comment by rodrigc** [comment]
@dstufft based on what  @mlouielu posted here https://github.com/python/core-workflow/issues/174#issuecomment-324548609 , do you know how this can be solved for blurb?  Can we remove older versions of blurb from PyPI?

**Comment by brettcannon** [comment]
There's a "remove" button in PyPI that I can try using. @larryhastings any issue if I try to remove the 1.0.0 and 0.0.0 releases?

**Comment by dstufft** [comment]
Yes, if the old versions didn't fail on 2.7 or didn't include the ``requires-python`` metadata your only options are to live with it or remove them.

**Comment by rodrigc** [comment]
@dstufft thanks for the feedback.  @larryhastings can you remove the offending packagees from PyPI or permit @brettcannon to do so?

**Comment by rodrigc** [comment]
@brettcannon I think this works now.  If I do this with Python 2.7:

```
» pip install blurb
Collecting blurb
  Could not find a version that satisfies the requirement blurb (from versions: )
No matching distribution found for blurb
```

If I do this with Python 3.4.6:

```
Collecting blurb
  Could not find a version that satisfies the requirement blurb (from versions: )
No matching distribution found for blurb
```


If I do this with Python 3.6:

```
» pip install blurb
Collecting blurb
  Downloading blurb-1.0.5-py3-none-any.whl (59kB)
    100% |████████████████████████████████| 61kB 2.9MB/s 
Installing collected packages: blurb
Successfully installed blurb-1.0.5
```
```

**Comment by rodrigc** [comment]
More verbose:

With Python 2.7:

```
```

With Python 3.4:

```
» pip install blurb -v
Collecting blurb
  1 location(s) to search for versions of blurb:
  * https://pypi.python.org/simple/blurb/
  Getting page https://pypi.python.org/simple/blurb/
  Looking up "https://pypi.python.org/simple/blurb/" in the cache
  Current age based on date: 419
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 419
  Analyzing links from page https://pypi.python.org/simple/blurb/
    The package https://pypi.python.org/packages/05/41/dfaf65e3a013b1ab4cad9d6f7b3be8bf02a94c3e4a27167df244eddbdaf4/blurb-1.0.5-py3-none-any.whl#md5=17a0f8c6b270bd5b7b26e61e5475e0b6 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/0b/f6/e7cd43f9c3d582e5640dffe6f266694ac78ee45712993a7efeb6099650be/blurb-1.0.2.dev1-py3-none-any.whl#md5=d240df35570e23971cbf8b3058c1d6e1 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/23/6d/62f98dc0e916235185874cb1fcb7db375fff498aec3c1389493a9414a42e/blurb-1.0.5.tar.gz#md5=df26dd5dafca90274ff5c587226b1a5d (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/2b/23/51a7bc8a9dc6fe04ba5635c96000c93e738bfe4d11e008b0c04bc5e519bc/blurb-1.0.1.post1-py3-none-any.whl#md5=114f7f9d3851d6e9cef2ab1d0b351ac4 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/32/dd/0a5e12bd32380fda9229eec68d5a3b2da014ebca8075ecf8cd3c4b18bab8/blurb-1.0.1.post1.tar.gz#md5=00380bc2a84870c5a6e0cc4e83ea7636 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/3d/d3/b17ae953f530f9287e29e86acaec4c6a858eae576ae487f3348edbd0b6af/blurb-1.0.0.post1.tar.gz#md5=082bb8a9edffff0b9095327c1f7ca860 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.6
    The package https://pypi.python.org/packages/4b/f3/76ea04c73110e5b936c1e164e5cbdbbebb6fb0a239b0b9198a932ec17bda/blurb-1.0.4.tar.gz#md5=7b730fc19cc412fc66ffdba7bd261473 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/59/3f/7fad7eb4044573c3c442945b8efd97b70a65392a0290c3c10552d8d122a9/blurb-1.0.1-py3-none-any.whl#md5=a6e52e66796167012b09af71b795584d (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.6
    The package https://pypi.python.org/packages/81/38/9c55685c7162dcaace7a034ff97e2c0253c965501378bd703479da9c282b/blurb-1.0.1.tar.gz#md5=cd3cc72ee9465a371f1f609fb87a0130 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.6
    The package https://pypi.python.org/packages/b8/ac/bf076a991f9c38eb7c140eebeffb2d9f6ae1c18b4673862461aa572a43ec/blurb-1.0.2.dev1.tar.gz#md5=bfda3e4deae686c122a5ff10ea0ae6c8 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/bc/92/ce7ffb09fc98975a4718acc89e180e6e8410f8beb518f4fbcb55af2005eb/blurb-1.0.0.post1-py3-none-any.whl#md5=4faf1d37bbb17502b5471dfa84ada12e (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.6
    The package https://pypi.python.org/packages/be/52/acf0440fd5107f4ffb104d4cf376542f648aa3933a82753ca9590a814147/blurb-1.0.4-py3-none-any.whl#md5=b0ea6f7f34345e34412e0037168fa9ad (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/c2/27/6bb9429bc126e6796a25eabbf3f472170e99d68aa2b3a8372f7a13e1babc/blurb-1.0.3-py3-none-any.whl#md5=3ffec5130dad3f85e6f4c8825d9b96e3 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://pypi.python.org/packages/ee/be/62c216959f57c97d277c730978b06beb0a9ce0ffc7dcaa83535ab6440c6e/blurb-1.0.3.tar.gz#md5=90c936b71fd46667a67a3945b7107b16 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
  Could not find a version that satisfies the requirement blurb (from versions: )
Cleaning up...
No matching distribution found for blurb
Exception information:
Traceback (most recent call last):
  File "/Users/c-craigr/.pyenv/versions/3.4.6/envs/venv-3.4.6/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/c-craigr/.pyenv/versions/3.4.6/envs/venv-3.4.6/lib/python3.4/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Users/c-craigr/.pyenv/versions/3.4.6/envs/venv-3.4.6/lib/python3.4/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/c-craigr/.pyenv/versions/3.4.6/envs/venv-3.4.6/lib/python3.4/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/Users/c-craigr/.pyenv/versions/3.4.6/envs/venv-3.4.6/lib/python3.4/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/c-craigr/.pyenv/versions/3.4.6/envs/venv-3.4.6/lib/python3.4/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for blurb
```

With Python 3.6:

```
» pip install blurb -v
Collecting blurb
  1 location(s) to search for versions of blurb:
  * https://pypi.python.org/simple/blurb/
  Getting page https://pypi.python.org/simple/blurb/
  Looking up "https://pypi.python.org/simple/blurb/" in the cache
  Current age based on date: 342
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 342
  Analyzing links from page https://pypi.python.org/simple/blurb/
    Found link https://pypi.python.org/packages/05/41/dfaf65e3a013b1ab4cad9d6f7b3be8bf02a94c3e4a27167df244eddbdaf4/blurb-1.0.5-py3-none-any.whl#md5=17a0f8c6b270bd5b7b26e61e5475e0b6 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.5
    Found link https://pypi.python.org/packages/0b/f6/e7cd43f9c3d582e5640dffe6f266694ac78ee45712993a7efeb6099650be/blurb-1.0.2.dev1-py3-none-any.whl#md5=d240df35570e23971cbf8b3058c1d6e1 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.2.dev1
    Found link https://pypi.python.org/packages/23/6d/62f98dc0e916235185874cb1fcb7db375fff498aec3c1389493a9414a42e/blurb-1.0.5.tar.gz#md5=df26dd5dafca90274ff5c587226b1a5d (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.5
    Found link https://pypi.python.org/packages/2b/23/51a7bc8a9dc6fe04ba5635c96000c93e738bfe4d11e008b0c04bc5e519bc/blurb-1.0.1.post1-py3-none-any.whl#md5=114f7f9d3851d6e9cef2ab1d0b351ac4 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.1.post1
    Found link https://pypi.python.org/packages/32/dd/0a5e12bd32380fda9229eec68d5a3b2da014ebca8075ecf8cd3c4b18bab8/blurb-1.0.1.post1.tar.gz#md5=00380bc2a84870c5a6e0cc4e83ea7636 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.1.post1
    Found link https://pypi.python.org/packages/3d/d3/b17ae953f530f9287e29e86acaec4c6a858eae576ae487f3348edbd0b6af/blurb-1.0.0.post1.tar.gz#md5=082bb8a9edffff0b9095327c1f7ca860 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6), version: 1.0.0.post1
    Found link https://pypi.python.org/packages/4b/f3/76ea04c73110e5b936c1e164e5cbdbbebb6fb0a239b0b9198a932ec17bda/blurb-1.0.4.tar.gz#md5=7b730fc19cc412fc66ffdba7bd261473 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.4
    Found link https://pypi.python.org/packages/59/3f/7fad7eb4044573c3c442945b8efd97b70a65392a0290c3c10552d8d122a9/blurb-1.0.1-py3-none-any.whl#md5=a6e52e66796167012b09af71b795584d (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6), version: 1.0.1
    Found link https://pypi.python.org/packages/81/38/9c55685c7162dcaace7a034ff97e2c0253c965501378bd703479da9c282b/blurb-1.0.1.tar.gz#md5=cd3cc72ee9465a371f1f609fb87a0130 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6), version: 1.0.1
    Found link https://pypi.python.org/packages/b8/ac/bf076a991f9c38eb7c140eebeffb2d9f6ae1c18b4673862461aa572a43ec/blurb-1.0.2.dev1.tar.gz#md5=bfda3e4deae686c122a5ff10ea0ae6c8 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.2.dev1
    Found link https://pypi.python.org/packages/bc/92/ce7ffb09fc98975a4718acc89e180e6e8410f8beb518f4fbcb55af2005eb/blurb-1.0.0.post1-py3-none-any.whl#md5=4faf1d37bbb17502b5471dfa84ada12e (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.6), version: 1.0.0.post1
    Found link https://pypi.python.org/packages/be/52/acf0440fd5107f4ffb104d4cf376542f648aa3933a82753ca9590a814147/blurb-1.0.4-py3-none-any.whl#md5=b0ea6f7f34345e34412e0037168fa9ad (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.4
    Found link https://pypi.python.org/packages/c2/27/6bb9429bc126e6796a25eabbf3f472170e99d68aa2b3a8372f7a13e1babc/blurb-1.0.3-py3-none-any.whl#md5=3ffec5130dad3f85e6f4c8825d9b96e3 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.3
    Found link https://pypi.python.org/packages/ee/be/62c216959f57c97d277c730978b06beb0a9ce0ffc7dcaa83535ab6440c6e/blurb-1.0.3.tar.gz#md5=90c936b71fd46667a67a3945b7107b16 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5), version: 1.0.3
  Using version 1.0.5 (newest of versions: 1.0.0.post1, 1.0.1, 1.0.1.post1, 1.0.3, 1.0.4, 1.0.5)
  Looking up "https://pypi.python.org/packages/05/41/dfaf65e3a013b1ab4cad9d6f7b3be8bf02a94c3e4a27167df244eddbdaf4/blurb-1.0.5-py3-none-any.whl" in the cache
  Current age based on date: 299
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 299
  Using cached blurb-1.0.5-py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/05/41/dfaf65e3a013b1ab4cad9d6f7b3be8bf02a94c3e4a27167df244eddbdaf4/blurb-1.0.5-py3-none-any.whl#md5=17a0f8c6b270bd5b7b26e61e5475e0b6 (from https://pypi.python.org/simple/blurb/) (requires-python:>=3.5)
Installing collected packages: blurb

  changing mode of /Users/c-craigr/venv-3.6/bin/blurb to 755
Successfully installed blurb-1.0.5
Cleaning up...
```
```
```

**Comment by rodrigc** [comment]
@brettcannon thanks!
