### ISSUE TITLE
blurb release fails with Reloading xxx isn't reproducable AssertionError

### ISSUE THREAD

**Issue by ned-deily** [python/core-workflow#205]
I ran across this error when creating the recent 3.6.3rc1 and 3.7.0a3 releases.  I spent a little bit of time investigating but, due to time constraints, I ignored the problem.  After committing the consolidated blurbs for those releases, blurb release no longer fails for those branches.  However, the problem still persists for the 2.7 branch which hasn't had a recent release.  One way to demonstrate the problem:

```
# checkout prior to tagging 3.6.3rc1
$ git checkout d9cadc5f597e5966132c9249f6c7ff0ed1eba0cb
$ blurb release 3.6.8
Merging 110 blurbs to "Misc/NEWS.d/3.6.8.rst".
Saving.
Traceback (most recent call last):
  File "/usr/local/bin/blurb", line 11, in <module>
    sys.exit(main())
  File "/home/nad/blurb-venv/lib/python3.6/site-packages/blurb.py", line 1562, in main
    sys.exit(fn(*filtered_args, **kwargs))
  File "/home/nad/blurb-venv/lib/python3.6/site-packages/blurb.py", line 943, in release
    assert blurbs2 == blurbs, "Reloading {} isn't reproducable?!".format(output)
AssertionError: Reloading Misc/NEWS.d/3.6.8.rst isn't reproducable?!

```
One possible clue: these are the first *blurb releases* run after a change from Daylight Savings Time.

(Noted in passing: reproducable -> reproducible.)

**Comment by larryhastings** [comment]
Thanks for the easy reproducable test case!  I mean, reproducible.

I like your debugging spidey-sense, but nope that's not the problem.

In this section of code, blurb is doing a sanity-check: having created a "release" .rst, it saves it to disk, then reloads it, and asserts that the two blurb objects (the original, and the freshly-loaded) are identical.  The problem is that one of the text bodies has gotten re-word-wrapped and a \n has shifted over by a word.

Original:
'io.FileIO.readall() and io.FileIO.read() now release the GIL when getting\nthe file size. Fixed hang of all threads with inaccessible NFS server.\nPatch by Nir Soffer.\n'

Reloaded:
'io.FileIO.readall() and io.FileIO.read() now release the GIL when getting\nthe file size. Fixed hang of all threads with inaccessible NFS server. Patch\nby Nir Soffer.\n'

Note the "\n" has moved from before the word "Patch" to after it.

I'm surprised; blurb already pretty aggressively reflows text.

If this is on fire, I can check in a cheap fix (strip all newlines from the text of the two files).  A more proper fix would be to make sure the text was consistently reflowed everywhere.

By the way, this sanity check happens *before* the "next" files are queued for "git rm".  So if you've hit this problem, sorry for having to clean those up manually.  I'll move the git rm queuing to after the sanity check Just In Case.
