### ISSUE TITLE
blurb: Quitting blurb without saving the original message results in KeyError

### ISSUE THREAD

**Issue by ericvsmith** [python/core-workflow#399]
To reproduce in blurb 1.0.8: Run blurb. Exit the editor without saving any changes.

Result: a traceback with a KeyError:

$ blurb
Traceback (most recent call last):
  File "/home/eric/venvs/py/bin/blurb", line 8, in <module>
    sys.exit(main())
  File "/home/eric/venvs/py/lib/python3.8/site-packages/blurb.py", line 1651, in main
    sys.exit(fn(*filtered_args, **kwargs))
  File "/home/eric/venvs/py/lib/python3.8/site-packages/blurb.py", line 954, in add
    blurb.load(tmp_path)
  File "/home/eric/venvs/py/lib/python3.8/site-packages/blurb.py", line 553, in load
    self.parse(text, metadata=metadata, filename=filename)
  File "/home/eric/venvs/py/lib/python3.8/site-packages/blurb.py", line 543, in parse
    finish_entry()
  File "/home/eric/venvs/py/lib/python3.8/site-packages/blurb.py", line 495, in finish_entry
    throw("Blurb 'body' text must not be empty!")
  File "/home/eric/venvs/py/lib/python3.8/site-packages/blurb.py", line 486, in throw
    raise BlurbError(f("Error in {filename}:{line_number}:\n{s}"))
  File "/home/eric/venvs/py/lib/python3.8/site-packages/blurb.py", line 138, in f
    return s.format_map(d)
KeyError: 'filename'

**Comment by ericvsmith** [comment]
This is a duplicate of #299. Closing.
